"""
models/expense.py — Expense Data Models
=========================================
Purpose:
    Pydantic models (schemas) for expense data.
    These define the exact shape of data coming IN from the frontend
    (request bodies) and going OUT to the frontend (response bodies).
    FastAPI uses these for automatic validation and API documentation.

    Three models per resource is standard FastAPI pattern:
    - Base       → shared fields
    - Create     → what the frontend sends to create a new record
    - Response   → what we send back (includes id, timestamps, etc.)
"""

from pydantic import BaseModel, Field
from typing import Optional


class ExpenseBase(BaseModel):
    """Fields shared by create and response models."""
    business_id:  int    = Field(..., description="Which business this expense belongs to")
    date:         str    = Field(..., description="Date of expense (YYYY-MM-DD)")
    vendor:       str    = Field(..., description="Vendor or payee name")
    amount:       float  = Field(..., gt=0, description="Amount in USD (must be positive)")
    category:     str    = Field(..., description="IRS expense category")
    description:  Optional[str]   = Field(None, description="Optional description or notes")
    notes:        Optional[str]   = Field(None, description="Freeform notes added by the user, separate from description")
    deductible:   bool            = Field(True, description="Is this expense tax deductible?")
    confidence:   str             = Field("high", description="Categorization confidence: high/medium/low")
    needs_review: bool            = Field(False, description="Flag for manual review")
    receipt_path: Optional[str]   = Field(None, description="Path to uploaded receipt file")
    split_group:  Optional[str]   = Field(None, description="Shared id linking rows created by splitting one expense; null if not split")


class ExpenseCreate(ExpenseBase):
    """
    What the frontend sends when creating a new expense.
    Inherits all fields from ExpenseBase.
    id and timestamps are generated by the database, not sent by the client.

    document_id is not a column on the expenses table — it's the id of a
    documents row (from an upload) to link to this expense once it's
    created, so the receipt can be previewed/edited from the Expenses page.
    """
    document_id: Optional[int] = Field(None, description="Linked documents.id from an upload, if any")


class ExpenseUpdate(BaseModel):
    """
    What the frontend sends when updating an existing expense.
    All fields are optional — only send what changed.
    """
    date:         Optional[str]   = None
    vendor:       Optional[str]   = None
    amount:       Optional[float] = Field(None, gt=0)
    category:     Optional[str]   = None
    description:  Optional[str]   = None
    notes:        Optional[str]   = None
    deductible:   Optional[bool]  = None
    confidence:   Optional[str]   = None
    needs_review: Optional[bool]  = None
    receipt_path: Optional[str]   = None


class ExpenseResponse(ExpenseBase):
    """
    What we send back to the frontend.
    Adds database-generated fields: id and timestamps.
    """
    id:         int
    created_at: str
    updated_at: str

    class Config:
        # Allows Pydantic to read data from sqlite3.Row objects
        # (which behave like dicts but aren't exactly dicts)
        from_attributes = True


class ExpenseSplitItem(BaseModel):
    """One line item within a split — amounts across all items must sum to the original expense's amount."""
    category:    str            = Field(..., description="Category for this portion")
    amount:      float          = Field(..., gt=0, description="Amount for this portion (must be positive)")
    description: Optional[str]  = Field(None, description="Optional description for this portion")
    deductible:  bool           = Field(True, description="Is this portion tax deductible?")


class ExpenseSplitRequest(BaseModel):
    """Body for POST /api/expenses/{id}/split — at least 2 line items required."""
    splits: list[ExpenseSplitItem] = Field(..., min_length=2, description="The line items to split this expense into")