"""
routes/luca.py — Luca Chat API Endpoints
===========================================
Purpose:
    Exposes Luca's capabilities to the frontend via HTTP routes.
    This file implements the 5-step answer construction from
    Bible Section 10.19 for knowledge questions:
        1. Retrieve fixed verified entry (rag_engine.search)
        2. AI personalizes framing (luca.chat with knowledge.txt prompt)
        3. Connect to user's logged data (future module — not yet built)
        4. Hardcoded source citation + disclaimer (injected by CODE,
           never by the AI — this is non-negotiable for trust/safety)
        5. Suggest next step

Connections:
    - Uses: rag_engine.py (knowledge search), engine.py (LucaEngine.chat)
    - Wired into: main.py via app.include_router()
    - Called by: frontend/src/services/api.js
"""

from fastapi import APIRouter
from pydantic import BaseModel
from backend.app.luca.rag_engine import rag_engine
from backend.app.luca.engine import luca, load_prompt
from backend.app.logger import get_logger

logger = get_logger()

router = APIRouter(prefix="/api/luca", tags=["luca"])


# ── Request/response models ───────────────────────────────────────────────────
# Pydantic models define the exact shape of data coming in and going out.
# FastAPI uses these to validate requests automatically and generate docs.

class AskRequest(BaseModel):
    """What the frontend sends when a user asks Luca a question."""
    question: str


class AskResponse(BaseModel):
    """What we send back to the frontend."""
    answered: bool           # True if we found verified info, False if not
    answer: str               # Luca's response text (includes disclaimer if answered)
    source: str | None = None       # Citation, e.g. "IRS Publication 535"
    topic: str | None = None        # Knowledge base topic category
    confidence_note: str | None = None  # Shown when answered=False


# ── The hardcoded disclaimer — NEVER generated by the AI ──────────────────────
# Per Bible Section 10.19, this is injected by code every single time,
# so it can never be skipped, altered, or "forgotten" by the model.
CPA_DISCLAIMER = (
    "\n\n---\n"
    "*This information is for general education only and is not tax, "
    "financial, or legal advice. Please confirm with your CPA, CFP, or "
    "tax advisor before making decisions based on this information.*"
)

NO_MATCH_RESPONSE = (
    "I don't have verified information on that topic in my knowledge base "
    "yet, so I don't want to guess and risk giving you something inaccurate. "
    "This is exactly the kind of question your CPA or tax advisor can answer "
    "with confidence — I'd recommend asking them directly."
)


@router.post("/ask", response_model=AskResponse)
async def ask_luca(request: AskRequest) -> AskResponse:
    """
    Main endpoint for educational tax questions.

    Implements the 5-step answer construction:
    1. Search the verified knowledge base for a matching entry
    2. If found, ask Luca to explain it conversationally (AI personalizes)
    3. (Future) Connect to the user's actual logged business data
    4. Append the hardcoded source + disclaimer (code, not AI)
    5. Luca's response naturally suggests a next step via the prompt
    """
    logger.info(f"Luca /ask received question: {request.question}")

    # STEP 1 — Retrieve fixed verified entry
    match = rag_engine.search(request.question)

    # STEP 4 (early exit) — No match found, return safe fallback
    # This is the anti-hallucination safety net: if nothing verified
    # matches, Luca refuses to guess rather than risk being wrong.
    if match is None:
        logger.info("No knowledge base match — returning safe fallback")
        return AskResponse(
            answered=False,
            answer=NO_MATCH_RESPONSE,
            confidence_note="No verified knowledge base entry matched this question."
        )

    # STEP 2 — AI personalizes the framing using ONLY the verified content
    knowledge_prompt_template = load_prompt("knowledge.txt")
    filled_prompt = knowledge_prompt_template.format(
        verified_content=match["content"],
        user_question=request.question
    )

    luca_result = await luca.chat(
        user_message=request.question,
        system_prompt=filled_prompt
    )

    if not luca_result["success"]:
        # Ollama itself failed (e.g. not running) — different failure mode
        # than "no knowledge match". Still never invent an answer.
        logger.error(f"Luca engine failed: {luca_result['error']}")
        return AskResponse(
            answered=False,
            answer=(
                "I found relevant information but I'm having trouble "
                "generating a response right now. Please make sure Ollama "
                "is running, or try again in a moment."
            ),
            confidence_note=luca_result["error"]
        )

    # STEP 4 — Hardcoded source citation + disclaimer, injected by CODE.
    # This line is what guarantees the disclaimer can never be skipped,
    # regardless of what the AI model generates.
    final_answer = (
        f"{luca_result['response']}\n\n"
        f"**Source:** {match['source']}"
        f"{CPA_DISCLAIMER}"
    )

    logger.info(f"Luca answered using knowledge entry: {match['title']}")

    return AskResponse(
        answered=True,
        answer=final_answer,
        source=match["source"],
        topic=match["topic"]
    )