"""
routes/luca.py — Luca Chat API Endpoints
===========================================
Purpose:
    Exposes Luca's capabilities to the frontend via HTTP routes.
    Implements the 5-step answer construction from Bible Section 10.19.

Changes in this version:
    - AskRequest now accepts `messages` (conversation history)
      so Luca knows what was said earlier in the session
    - Greeting detection now checks if it's the FIRST message —
      Luca only says Hi once per session, not on every message
    - Conversation history is formatted and injected into the
      knowledge.txt prompt so Luca's answers are contextual
    - Business name from user context is passed when available

Connections:
    - Uses: rag_engine.py (knowledge search), engine.py (LucaEngine.chat)
    - Wired into: main.py via app.include_router()
    - Called by: frontend/src/services/api.js
"""

from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Optional
import re
from backend.app.luca.rag_engine import rag_engine
from backend.app.luca.engine import luca, load_prompt
from backend.app.logger import get_logger

logger = get_logger()

router = APIRouter(prefix="/api/luca", tags=["luca"])


# ── Request/response models ───────────────────────────────────────────────────

class MessageHistory(BaseModel):
    """A single message in the conversation history."""
    role: str   # "user" or "luca"
    text: str


class AskRequest(BaseModel):
    """What the frontend sends when a user asks Luca a question."""
    question: str
    messages: Optional[List[MessageHistory]] = []  # Conversation history
    business_name: Optional[str] = None            # User's business name if known


class AskResponse(BaseModel):
    """What we send back to the frontend."""
    answered: bool
    answer: str
    source: str | None = None
    topic: str | None = None
    confidence_note: str | None = None


# ── The hardcoded disclaimer — NEVER generated by the AI ──────────────────────
CPA_DISCLAIMER = (
    "\n\n---\n"
    "*This information is for general education only and is not tax, "
    "financial, or legal advice. Please confirm with your CPA, CFP, or "
    "tax advisor before making decisions based on this information.*"
)

NO_MATCH_RESPONSE = (
    "I don't have verified information on that topic in my knowledge base "
    "yet, so I don't want to guess and risk giving you something inaccurate. "
    "This is exactly the kind of question your CPA or tax advisor can answer "
    "with confidence — I'd recommend asking them directly."
)

_CONVERSATIONAL_EXACT = {
    "hello", "hi", "hey", "hiya", "howdy", "yo",
    "good morning", "good afternoon", "good evening",
    "thanks", "thank you", "ty", "thx",
    "help", "what can you do", "what do you do",
    "who are you",
}


def _is_first_message(messages: List[MessageHistory]) -> bool:
    """True if this is the very first user message in the session."""
    # Count only user messages in history (excluding the current one)
    user_messages = [m for m in messages if m.role == "user"]
    return len(user_messages) == 0


def _is_conversational(question: str) -> bool:
    """Greetings and small talk — answer with Luca's base personality, not the KB."""
    text = re.sub(r"[!?.]+$", "", question.strip().lower()).strip()
    if text in _CONVERSATIONAL_EXACT:
        return True
    if len(text.split()) <= 6 and text.startswith(("hi ", "hello ", "hey ", "thanks ")):
        return True
    return False


def _format_conversation_history(messages: List[MessageHistory], max_turns: int = 6) -> str:
    """
    Format recent conversation history into a string for the prompt.
    Only includes the last N turns to keep the context window manageable.

    Args:
        messages: Full conversation history from the frontend
        max_turns: Maximum number of messages to include (default 6 = 3 exchanges)

    Returns:
        Formatted string of the conversation, or empty string if no history
    """
    if not messages:
        return ""

    # Take the most recent messages up to max_turns
    recent = messages[-max_turns:]

    lines = []
    for msg in recent:
        if msg.role == "user":
            lines.append(f"User: {msg.text}")
        elif msg.role == "luca":
            # Truncate Luca's previous responses to avoid bloating the prompt
            truncated = msg.text[:300] + "..." if len(msg.text) > 300 else msg.text
            lines.append(f"Luca: {truncated}")

    return "\n".join(lines)


def _ollama_failure_response(error: str) -> AskResponse:
    if "not running" in error.lower():
        user_message = (
            "I'm having trouble reaching Ollama. "
            "Please start the Ollama app and try again."
        )
    elif "memory" in error.lower():
        user_message = (
            "The AI model could not load into memory. "
            "Try restarting Ollama or closing other apps, then ask again."
        )
    elif "too long to respond" in error.lower():
        user_message = error
    else:
        user_message = (
            "I'm having trouble generating a response right now. "
            "Please try again in a moment."
        )
    return AskResponse(
        answered=False,
        answer=user_message,
        confidence_note=error,
    )


@router.post("/ask", response_model=AskResponse)
async def ask_luca(request: AskRequest) -> AskResponse:
    """
    Main endpoint for educational tax questions.

    Now accepts conversation history so Luca can maintain context
    across the session and avoid re-greeting on every message.
    """
    logger.info(f"Luca /ask received question: {request.question}")

    # Format conversation history for context injection
    history_str = _format_conversation_history(request.messages or [])
    is_first = _is_first_message(request.messages or [])

    # STEP 1 — Retrieve fixed verified entry
    match = rag_engine.search(request.question)

    # ── Greetings / small talk ────────────────────────────────────────────────
    # Only treat as conversational if it's actually a greeting AND it's
    # the first message. If the user says "hi" mid-conversation, still
    # respond naturally but don't trigger the full greeting sequence.
    if _is_conversational(request.question):
        logger.info("Conversational message — using base Luca prompt")

        if is_first:
            # First message greeting — use base prompt as-is
            luca_result = await luca.chat(user_message=request.question)
        else:
            # Mid-conversation small talk — include history for context
            mid_prompt = load_prompt("base.txt")
            if history_str:
                mid_prompt = (
                    f"{mid_prompt}\n\n"
                    f"Conversation so far:\n{history_str}\n\n"
                    f"Continue naturally. Do not re-introduce yourself."
                )
            luca_result = await luca.chat(
                user_message=request.question,
                system_prompt=mid_prompt
            )

        if not luca_result["success"]:
            logger.error(f"Luca engine failed: {luca_result['error']}")
            return _ollama_failure_response(luca_result["error"])
        return AskResponse(
            answered=True,
            answer=luca_result["response"].strip(),
        )

    # ── No knowledge base match ───────────────────────────────────────────────
    if match is None:
        logger.info("No knowledge base match — returning safe fallback")

        # If we have conversation context, give a more natural fallback
        if history_str:
            contextual_fallback = (
                "I don't have verified information on that specific topic in my "
                "knowledge base yet. I'd rather point you to your CPA than risk "
                "giving you something inaccurate. Is there something else I can "
                "help you with?"
            )
        else:
            contextual_fallback = NO_MATCH_RESPONSE

        return AskResponse(
            answered=False,
            answer=contextual_fallback,
            confidence_note="No verified knowledge base entry matched this question."
        )

    # ── STEP 2 — AI personalizes the framing with verified content + history ──
    knowledge_prompt_template = load_prompt("knowledge.txt")

    # Inject conversation history into the knowledge prompt if available
    # This lets Luca reference earlier context ("As I mentioned..." etc.)
    history_context = ""
    if history_str and not is_first:
        history_context = (
            f"\n\nConversation history (for context only — "
            f"do not repeat what was already said):\n{history_str}\n"
        )

    # Add business name context if provided
    business_context = ""
    if request.business_name:
        business_context = (
            f"\n\nThe user's business is called '{request.business_name}'. "
            f"You may reference it naturally if relevant."
        )

    filled_prompt = (
        knowledge_prompt_template.format(
            verified_content=match["content"],
            user_question=request.question
        )
        + history_context
        + business_context
    )

    luca_result = await luca.chat(
        user_message=request.question,
        system_prompt=filled_prompt
    )

    if not luca_result["success"]:
        logger.error(f"Luca engine failed: {luca_result['error']}")
        return _ollama_failure_response(luca_result["error"])

    # STEP 4 — Hardcoded source citation + disclaimer, injected by CODE
    final_answer = (
        f"{luca_result['response']}\n\n"
        f"**Source:** {match['source']}"
        f"{CPA_DISCLAIMER}"
    )

    logger.info(f"Luca answered using knowledge entry: {match['title']}")

    return AskResponse(
        answered=True,
        answer=final_answer,
        source=match["source"],
        topic=match["topic"]
    )


# ── Categorize endpoint ───────────────────────────────────────────────────────

class CategorizeRequest(BaseModel):
    vendor: str
    amount: float
    description: str = ""
    transaction_type: str = "expense"   # "expense" or "income" — picks which prompt/category set to use


class CategorizeResponse(BaseModel):
    category: str
    confidence: str
    deductible: bool
    notes: str
    needs_review: bool
    success: bool


@router.post("/categorize", response_model=CategorizeResponse)
async def categorize_expense(request: CategorizeRequest) -> CategorizeResponse:
    """
    Ask Luca to suggest a category for an expense or income transaction.
    transaction_type="expense" (default) uses categorize.txt (IRS expense categories).
    transaction_type="income" uses categorize_income.txt (income source categories).
    """
    logger.info(f"Categorize request ({request.transaction_type}): {request.vendor} ${request.amount}")

    prompt_file = "categorize_income.txt" if request.transaction_type == "income" else "categorize.txt"
    categorize_prompt = load_prompt(prompt_file)

    user_message = (
        f"Vendor: {request.vendor}\n"
        f"Amount: ${request.amount:.2f}\n"
        f"Description: {request.description or 'Not provided'}"
    )

    result = await luca.chat(
        user_message=user_message,
        system_prompt=categorize_prompt
    )

    fallback_category = "Other Income" if request.transaction_type == "income" else "Uncategorized"

    if not result["success"]:
        logger.error(f"Categorization failed: {result['error']}")
        return CategorizeResponse(
            category=fallback_category,
            confidence="low",
            deductible=False,
            notes="Luca could not categorize this transaction. Please categorize manually.",
            needs_review=True,
            success=False
        )

    import json
    import re
    try:
        raw = result["response"]
        json_match = re.search(r'\{.*\}', raw, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group())
            return CategorizeResponse(
                category=parsed.get("category", "Uncategorized"),
                confidence=parsed.get("confidence", "low"),
                deductible=bool(parsed.get("deductible", False)),
                notes=parsed.get("notes", ""),
                needs_review=bool(parsed.get("needs_review", True)),
                success=True
            )
    except Exception as e:
        logger.error(f"Failed to parse categorization JSON: {e} | raw: {raw}")

    return CategorizeResponse(
        category=fallback_category,
        confidence="low",
        deductible=False,
        notes="Could not parse Luca's response. Please categorize manually.",
        needs_review=True,
        success=False
    )